### ISSUE TITLE
Include gifs for all screens

### ISSUE THREAD

**Issue by fcrozetta** [fcrozetta/tui-netcore#13]
In the readme.md is necessary to add images for all options, to make it easier to understand and use

**Comment by fcrozetta** [comment]
Not static images, but gifs.
asciinema forces people to go to their page. a gif may be a better solution, if it works

**Comment by aleksaradz** [comment]
I started working on this issue with PR #15 and will send new PRs to add the animated gifs for the other screens

**Comment by aleksaradz** [comment]
@fcrozetta I don't see the links to asciicinema for the other images - can you post here please?

**Comment by fcrozetta** [comment]
@aleksaradz I created the asciinema for the every option.

**Comment by fcrozetta** [comment]
One additional things:
Since we have the gif now, its not necessary to link it to asciinema. Just the GIF will be OK

**Comment by aleksaradz** [comment]
Fantastic! Thank you so much for recording these asciicinemas @fcrozetta!

I converted all asciicasts to animated gifs and can send pullrequests to update the Readme (and remove the links to asciicinema as you asked)

I found this project through the `hacktoberfest` topic and I already have more than enough pullrequests accepted across GitHub so I think I will be generous and allow other developers to contribute to your project, learn how to contribute to opensource, and in doing so get credits for hacktoberfest

I will post all the animated gifs below for anyone that wants to take part in hacktoberfest. **If in the next 48 hours nobody takes them and sends to you as pullrequests, then I will do it myself**

![image](https://user-images.githubusercontent.com/72725560/96545176-e1945380-1275-11eb-905f-0268800d2d52.png)

**Comment by aleksaradz** [comment]
## Drawing an OK Box

![tui-netcore-draw-ok](https://user-images.githubusercontent.com/72725560/96545290-1a342d00-1276-11eb-859e-0007bd27f638.gif)

**Comment by aleksaradz** [comment]
## Drawing an Input Box

![tui-netcore-draw-input](https://user-images.githubusercontent.com/72725560/96545323-2b7d3980-1276-11eb-88f6-d570703a0649.gif)

**Comment by aleksaradz** [comment]
## Drawing a Yes/No Box

![tui-netcore-yes-no](https://user-images.githubusercontent.com/72725560/96545366-4059cd00-1276-11eb-92cf-07b1b2f14a8d.gif)

**Comment by aleksaradz** [comment]
## Drawing a Check Box

![tui-netcore-draw-checkbox](https://user-images.githubusercontent.com/72725560/96545392-4cde2580-1276-11eb-930d-8240f6cb5860.gif)

**Comment by aleksaradz** [comment]
## Drawing a List box

![tui-netcore-draw-listbox](https://user-images.githubusercontent.com/72725560/96545428-5bc4d800-1276-11eb-8fa0-dc8e451c8ea2.gif)

**Comment by aleksaradz** [comment]
## Drawing a Book box

![tui-netcore-draw-bookbox](https://user-images.githubusercontent.com/72725560/96545449-65e6d680-1276-11eb-8648-3faa74e91893.gif)

**Comment by victorgoebel** [comment]
Thank you @aleksaradz :+1:  !!! I created pull requests #22, #23, #24, #25 

Check Box, List Box, and Book Box are still available if anyone wants to get 3 pull requests in!! :partying_face:

**Comment by fcrozetta** [comment]
@victorgoebel 
Since all the requests are related to the same thing, please open only one PR to add the images. I will cancel those PRs so you can open only one, adding all the images :)

**Comment by victorgoebel** [comment]
Hi @fcrozetta. Sadly the [Hacktoberfest rules](https://hacktoberfest.digitalocean.com/#rules) are strict and they don't count the number of commits or the size of the contribution... They only give credit by counting the number of pull-requests.

@aleksaradz (good) intention was to provide multiple images that other contributors can use to create PR's back to your repository.

---

[_To earn your Hacktoberfest tee or tree reward, you must register and **make four valid pull requests (PRs)** between October 1-31 (in any time zone). PRs can be made to participating public repos on GitHub, those that have the Hacktoberfest topic_](https://hacktoberfest.digitalocean.com/#rules)

Can you re-open my PRs (and merge if I didn't miss anything)?

**Comment by fcrozetta** [comment]
Hey @victorgoebel !
Glad you are contributing to some open source projects!
aleksaradz did a great job, and was really kind to share it with someone who needs a PR to fulfill the project. However, the second rule of hacktoberfest says:

> 2. *Quantity is fun, quality is key*. Participating in Hacktoberfest leads to personal growth, professional opportunities, and community building. However, it all begins with meaningful contributions to open source software.

you can check it [here](https://hacktoberfest.digitalocean.com/details)

I understand that you need 4 PRs to complete the challenge, but adding 4 small updates that are essentially the same would be bad. If you are new to the challenge, don't worry. They ask only 4 PRs because the main point is contributing to the community, and not winning fast. There is also another issue on this project that asks for code examples in the documentation. If you want to get a second PR, you can work on that as well, and help you along the way, if you need

**Comment by victorgoebel** [comment]
I'm confused. Why was it OK for @aleksaradz to send you a small PR (identical to mine) https://github.com/fcrozetta/tui-netcore/pull/15 (**that you merged**) and gave her the credit towards Hacktoberfest, but my PR got rejected?

What is the difference between #15 and #23? :confused:

**Comment by fcrozetta** [comment]
I had to go back and check that i merged that PR. It was not supposed to be merged, and it was stated that it was only a sample.
*BUT*, since i made a mistake there, i don't believe it would be fair to you, so i will reopen and accept those PRs
Thanks for pointing out my mistake!
( your PRs #22 , #23, #24, #25 are merged into master)

**Comment by victorgoebel** [comment]
Thank you!
